url: https://y7kim.github.io
baseurl: /agency-jekyll-theme/

# Site settings
title: Rituparna Dey
email: deyritu20@gmail.com
description: "Portifolio Website Web HTML5 Javascript CSS PHP Wordpress Social Media"
# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503  
  secondary-dark: 333


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/twinkle_tia20
  - title: linkedin
    url: https://in.linkedin.com/in/rituparnadey

# Postal address (add as many lines as necessary)
address:
  - line: Pune
  - line: Maharashtra, India

# Build settings
markdown: kramdown
permalink: pretty